FROM ubuntu:latest

ARG RETHINKDB_SERVERS_URL

WORKDIR /app

RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-venv wget && \
    apt-get install -y libjpeg-turbo8-dev zlib1g-dev gcc python3-dev python3-dbg ffmpeg xfonts-base fonts-arphic-bkai00mp fonts-arphic-bsmi00lp fonts-arphic-gbsn00lp fonts-arphic-gkai00mp fonts-arphic-ukai fonts-farsiweb fonts-nafees fonts-sil-abyssinica fonts-sil-ezra fonts-sil-padauk fonts-unfonts-extra fonts-unfonts-core fonts-indic fonts-thai-tlwg fonts-lklug-sinhala fonts-liberation libnspr4 libnss3 xdg-utils

RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
    dpkg -i google-chrome-stable_current_amd64.deb

ENV SERVICE_NAME="brozzler-worker"

RUN useradd -ms /bin/bash $SERVICE_NAME && \
    mkdir -p /var/log/$SERVICE_NAME && \
    chown $SERVICE_NAME:$SERVICE_NAME /var/log/$SERVICE_NAME

WORKDIR /brozzler
RUN python3 -m venv /opt/brozzler-worker-venv
# Enable venv
ENV PATH="/opt/brozzler-worker-venv/bin:$PATH"

RUN pip install --upgrade pip && \
    pip install setuptools

COPY ./dev/brozzler-worker-entrypoint.sh /entrypoint.sh
COPY ./dev/run-brozzler-worker.sh /run-brozzler-worker.sh

ENTRYPOINT ["bash", "/entrypoint.sh"]