Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.define "10.9.9.9"
  config.vm.hostname = "brzl"
  config.vm.network :private_network, ip: "10.9.9.9"

  config.vm.synced_folder "..", "/brozzler"

  config.vm.provision "ansible" do |ansible|
    ansible.inventory_path = "ansible/hosts"
    ansible.playbook = "ansible/playbook.yml"
  end
end
