Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.define "10.9.9.9"
  config.vm.hostname = "brzl"
  config.vm.network :private_network, ip: "10.9.9.9"
  config.disksize.size = '50GB'

  config.vm.synced_folder "..", "/brozzler"

  # bump up memory to avoid "can't start new thread" errors
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end

  config.vm.provision "ansible" do |ansible|
    ansible.inventory_path = "../ansible/hosts-vagrant"
    ansible.playbook = "../ansible/playbook.yml"
    # ansible.verbose = "-vvv"
  end

  config.vm.provider 'virtualbox' do |v|
    v.name = 'brozzler-test-vm'
  end
end
