Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "brozzler-easy"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/playbook.yml"
    ansible.groups = {
      "rethinkdb" => ["default"],
      "warcprox" => ["default"],
      "brozzler-worker" => ["default"],
      # "brozzler-webconsole" => ["default"],
    }
  end
end
