name: Full test suite

on:
  schedule:
    - cron: "0 6 * * *" # 10PM Pacific daily

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 480
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - uses: ./.github/workflows/setup
        with:
          python-version: '3.12'

      - name: Run tests
        run: |
          uv run py.test --tb=native --verbose tests
