name: Python Formatting Check

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Create virtual environment
      run: python -m venv .venv

    - name: Install ruff
      run: |
        ./.venv/bin/pip install --upgrade pip
        ./.venv/bin/pip install ruff

    - name: Run check
      run: make check

    - name: Run formatting check
      run: make check-format
