name: Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['3.8', '3.12']
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version }}

      - uses: ./.github/workflows/setup

      - name: Run tests
        run: |
          py.test --tb=native --verbose tests/test_cli.py tests/test_units.py
