name: Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['3.9', '3.12', '3.14']
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - uses: ./.github/workflows/setup
        with:
          python-version: ${{ matrix.version }}

      - name: Run tests
        run: |
          uv run py.test --tb=native --verbose tests
